// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckProxy(arg1:string,arg2:string,arg3:string):Promise<main.CheckResult>;

export function DisableSystemProxy():Promise<string>;

export function FetchRealProxies(arg1:Array<string>):Promise<Array<main.Proxy>>;

export function GetSystemProxyExitIP():Promise<string>;

export function OpenProxyFile():Promise<string>;

export function SetLocalPort(arg1:string):Promise<void>;

export function SetSystemProxy(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartLocalMiddleware():Promise<void>;

export function ToggleKillSwitch(arg1:boolean,arg2:string,arg3:string,arg4:string):Promise<void>;
