// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckProxy'](arg1, arg2, arg3);
}

export function DisableSystemProxy() {
  return window['go']['main']['App']['DisableSystemProxy']();
}

export function FetchRealProxies(arg1) {
  return window['go']['main']['App']['FetchRealProxies'](arg1);
}

export function GetSystemProxyExitIP() {
  return window['go']['main']['App']['GetSystemProxyExitIP']();
}

export function OpenProxyFile() {
  return window['go']['main']['App']['OpenProxyFile']();
}

export function SetLocalPort(arg1) {
  return window['go']['main']['App']['SetLocalPort'](arg1);
}

export function SetSystemProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSystemProxy'](arg1, arg2, arg3);
}

export function StartLocalMiddleware() {
  return window['go']['main']['App']['StartLocalMiddleware']();
}

export function ToggleKillSwitch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToggleKillSwitch'](arg1, arg2, arg3, arg4);
}
